resolver: nightly-2017-12-13

packages:
- .

extra-include-dirs:
- C:\Users\sdl96354\AppData\Local\Programs\HaskellPlatform\8.0.2\msys\mingw64\include
extra-lib-dirs:
- C:\Users\sdl96354\AppData\Local\Programs\HaskellPlatform\8.0.2\msys\mingw64\lib
